import { Product, Testimonial, FAQItem } from '@/types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'classic-couple-gift',
    name: 'Classic Couple Set',
    nameTH: 'คู่รักคลาสสิก',
    description: 'Perfect gift for couples — two custom minifigures in a gift box',
    descriptionTH: 'เซ็ตคู่รักสุดพิเศษ สั่งทำ 2 ตัวพร้อมกล่องของขวัญสวยงาม เหมาะสำหรับวาเลนไทน์ ครบรอบ หรือวันเกิดคนพิเศษ',
    price: 1290,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1585378169254-e79b8c54e7ef?w=600&h=600&fit=crop',
    ],
    category: 'gift',
    gender: 'unisex',
    theme: 'valentine',
    badge: 'bestseller',
    preset: 'couple',
  },
  {
    id: '2',
    slug: 'wedding-figure',
    name: 'Wedding Cake Topper',
    nameTH: 'คู่บ่าวสาวงานแต่ง',
    description: 'Custom bride & groom minifigures as unique wedding cake toppers',
    descriptionTH: 'บ่าวสาวมินิฟิกเกอร์แบบกำหนดเอง เป็นที่ระลึกจากวันแต่งงานที่ไม่เหมือนใคร',
    price: 1590,
    images: [
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=600&h=600&fit=crop',
    ],
    category: 'wedding',
    gender: 'unisex',
    badge: 'bestseller',
    preset: 'wedding',
  },
  {
    id: '3',
    slug: 'office-hero',
    name: 'Office Hero',
    nameTH: 'ฮีโร่ออฟฟิศ',
    description: 'Custom minifigure in work outfit — great for desk decoration',
    descriptionTH: 'มินิฟิกเกอร์ใส่ชุดทำงาน เหมาะสำหรับตั้งโต๊ะออฟฟิศ หรือของขวัญเพื่อนร่วมงาน',
    price: 690,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1497366412874-3415097a27e7?w=600&h=600&fit=crop',
    ],
    category: 'gift',
    gender: 'unisex',
    badge: 'new',
    preset: 'office',
  },
  {
    id: '4',
    slug: 'gamer-figure',
    name: 'The Gamer',
    nameTH: 'นักเกม',
    description: 'Minifigure for gaming enthusiasts — complete with controller accessories',
    descriptionTH: 'สำหรับคนรักเกม พร้อมจอยเกมและอุปกรณ์ครบ',
    price: 790,
    images: [
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=600&fit=crop',
    ],
    category: 'collect',
    gender: 'male',
    badge: 'new',
    preset: 'gamer',
  },
  {
    id: '5',
    slug: 'nurse-figure',
    name: 'Hero in White',
    nameTH: 'ฮีโร่ชุดขาว',
    description: 'Honor healthcare workers with a custom nurse or doctor minifigure',
    descriptionTH: 'ของขวัญสุดพิเศษสำหรับบุคลากรทางการแพทย์ พยาบาล หมอ หรือทันตแพทย์',
    price: 690,
    images: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&h=600&fit=crop',
    ],
    category: 'gift',
    gender: 'female',
    preset: 'nurse',
  },
  {
    id: '6',
    slug: 'graduation-figure',
    name: 'Graduation Day',
    nameTH: 'วันรับปริญญา',
    description: 'Celebrate graduation with a custom figure in academic gown',
    descriptionTH: 'ฉลองความสำเร็จด้วยมินิฟิกเกอร์ชุดครุยพร้อมหมวกแบบพิเศษ',
    price: 790,
    images: [
      'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&h=600&fit=crop',
    ],
    category: 'gift',
    gender: 'unisex',
    badge: 'bestseller',
    preset: 'graduation',
  },
  {
    id: '7',
    slug: 'b2b-team-set',
    name: 'Team Collection',
    nameTH: 'เซ็ตทีมบริษัท',
    description: 'Bulk order for corporate gifting — minimum 10 pcs with logo base',
    descriptionTH: 'สั่งทำสำหรับบริษัทขั้นต่ำ 10 ชิ้น พร้อมฐานพิมพ์โลโก้บริษัท ราคาพิเศษ',
    price: 590,
    images: [
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&h=600&fit=crop',
    ],
    category: 'b2b',
    gender: 'unisex',
    badge: 'sale',
    preset: 'business',
  },
  {
    id: '8',
    slug: 'halloween-figure',
    name: 'Halloween Special',
    nameTH: 'ฮาโลวีนสเปเชียล',
    description: 'Spooky custom minifigure — perfect for Halloween gifting',
    descriptionTH: 'มินิฟิกเกอร์ธีมฮาโลวีน ผี แวมไพร์ หรือแม่มด กำหนดแบบได้เอง',
    price: 790,
    images: [
      'https://images.unsplash.com/photo-1509557965875-b88c97176a26?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1570303345338-e1f0eddf4946?w=600&h=600&fit=crop',
    ],
    category: 'collect',
    gender: 'unisex',
    theme: 'halloween',
    preset: 'halloween',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'คุณมาลี สุขใจ',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=mali&backgroundColor=b6e3f4',
    rating: 5,
    comment: 'สั่งทำเป็นของขวัญให้แฟนวันเกิด แกชอบมากเลย! รายละเอียดละเอียดมาก หน้าเหมือนแฟนจริงๆ บอกเลยว่าประทับใจมาก จะกลับมาสั่งอีกแน่นอนค่ะ 💛',
    date: '15 มี.ค. 2567',
    productName: 'คู่รักคลาสสิก',
  },
  {
    id: '2',
    name: 'คุณธนกร วรรณภูมิ',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=thanakorn&backgroundColor=ffd5dc',
    rating: 5,
    comment: 'สั่งเป็นของขวัญงานแต่งงาน ทำเป็น Cake Topper สวยมากครับ แขกทุกคนถามเลยว่าซื้อที่ไหน งานปริ้นคุณภาพดีกว่าที่คิดไว้มาก',
    date: '2 เม.ย. 2567',
    productName: 'คู่บ่าวสาวงานแต่ง',
  },
  {
    id: '3',
    name: 'คุณณัชชา พิทักษ์',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=natcha&backgroundColor=c0aede',
    rating: 5,
    comment: 'สั่งให้เพื่อนที่รับปริญญา ตัวการ์ตูนเหมือนมากๆ เพื่อนร้องไห้เลยค่ะ ส่งเร็วกว่าที่บอกด้วย ของขวัญที่ดีที่สุดในชีวิตเลยนะ!',
    date: '18 มี.ค. 2567',
    productName: 'วันรับปริญญา',
  },
  {
    id: '4',
    name: 'คุณสมชาย รักงาน',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=somchai&backgroundColor=d1d4f9',
    rating: 5,
    comment: 'สั่งทำสำหรับบริษัท 30 ชิ้น แจกพนักงานครบรอบ 10 ปี ทีมงาน BrickMe ดูแลดีมากครับ มีหัวหน้าทีมติดต่อตลอด ราคาคุ้มค่ามาก',
    date: '5 เม.ย. 2567',
    productName: 'เซ็ตทีมบริษัท',
  },
  {
    id: '5',
    name: 'คุณวิภาวี ใจดี',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=wipawee&backgroundColor=ffdfbf',
    rating: 5,
    comment: 'ของมันต้องมี! ทำแล้วรูปสวย แพ็คเกจสวยมาก เปิดแล้วปัง ราคาไม่แพงเลยสำหรับคุณภาพแบบนี้ แนะนำเพื่อนไปอีก 5 คนแล้วค่ะ',
    date: '20 เม.ย. 2567',
    productName: 'ฮีโร่ออฟฟิศ',
  },
]

export const FAQ_ITEMS: FAQItem[] = [
  {
    question: 'ใช้เวลาทำนานแค่ไหน?',
    questionEN: 'How long does production take?',
    answer: 'ปกติ 7–14 วันทำการหลังยืนยันแบบ โดยทีมงานจะส่งรูป QC ให้ดูก่อนจัดส่งทุกครั้ง หากต้องการเร่งสามารถแจ้งได้ มีค่าบริการ Rush +300 บาท',
    answerEN: 'Standard lead time is 7–14 business days after design confirmation. We always send QC photos before shipping. Rush orders available for +300 THB.',
  },
  {
    question: 'รับทำตัวละครจากการ์ตูน/หนังได้ไหม?',
    questionEN: 'Can you make licensed cartoon/movie characters?',
    answer: 'เราไม่รับทำ replica ตัวละครลิขสิทธิ์เพื่อการค้า (เช่น Marvel, Disney, Naruto) เพื่อเคารพสิทธิ์เจ้าของทรัพย์สินทางปัญญา แต่รับทำตัวละครที่ได้รับแรงบันดาลใจ หรือตัวละครที่คุณออกแบบเองได้เต็มที่',
    answerEN: 'We do not replicate licensed characters for commercial use. However, we can create original characters inspired by any style you love.',
  },
  {
    question: 'ขนาดเท่าไร? ใหญ่กว่า LEGO จริงไหม?',
    questionEN: 'What is the size? Is it bigger than real LEGO?',
    answer: 'ตัวละครมีความสูงประมาณ 6 ซม. (เท่ากับ LEGO Minifigure จริง) สำหรับรุ่น Chibi จะสูงกว่าเล็กน้อยที่ 7 ซม. และ Realistic Head สูงสุดที่ 7.5 ซม.',
    answerEN: 'Standard height is ~6cm (same as real LEGO). Chibi version is 7cm, Realistic Head is 7.5cm.',
  },
  {
    question: 'วัสดุอะไร? ทนไหม? กันน้ำไหม?',
    questionEN: 'What material? Is it durable? Waterproof?',
    answer: 'ใช้เรซิ่น UV Resin คุณภาพสูง ทนทาน ไม่แตกง่าย ทนต่อการหยิบจับปกติ แต่ไม่แนะนำให้แช่น้ำหรือโดนแดดจัดนานๆ เพื่อรักษาสีให้สดใสนาน',
    answerEN: 'We use high-quality UV Resin — durable for normal handling. Avoid prolonged water exposure or direct sunlight to preserve colors.',
  },
  {
    question: 'ส่งต่างจังหวัดได้ไหม? มีส่งต่างประเทศไหม?',
    questionEN: 'Do you ship nationwide? Internationally?',
    answer: 'ส่งทุกจังหวัดในประเทศไทยผ่าน Kerry, Flash, J&T และ EMS สำหรับต่างประเทศรับเฉพาะ EMS (ประมาณ 5–10 วัน ค่าส่งคิดตามน้ำหนักจริง)',
    answerEN: 'We ship nationwide via Kerry, Flash, J&T, and EMS. International shipping via EMS only (5–10 days, calculated by weight).',
  },
  {
    question: 'ยกเลิก/คืนเงินได้ไหม?',
    questionEN: 'Can I cancel or get a refund?',
    answer: 'ยกเลิกได้ฟรีภายใน 24 ชม. หลังชำระเงิน ถ้าเลยจากนั้นแต่ยังไม่เริ่มปริ้น คืนได้ 50% หลังเริ่มปริ้นแล้วไม่สามารถคืนเงินได้ เนื่องจากเป็นสินค้าสั่งทำพิเศษ',
    answerEN: 'Free cancellation within 24hrs. 50% refund if cancelled before printing starts. No refund after production begins.',
  },
  {
    question: 'แก้แบบหลังสั่งได้กี่ครั้ง?',
    questionEN: 'How many design revisions are allowed?',
    answer: 'สามารถแก้แบบได้ 2 ครั้งฟรีในขั้นตอน "ยืนยันแบบ" หากต้องการแก้เพิ่มมีค่าบริการครั้งละ 100 บาท',
    answerEN: '2 free revisions during the design confirmation step. Additional revisions cost 100 THB each.',
  },
  {
    question: 'ทำไมราคาต่างกัน?',
    questionEN: 'Why do prices vary?',
    answer: 'ราคาขึ้นอยู่กับสไตล์ (Classic/Chibi/Realistic), ประเภทฐาน, และอุปกรณ์เสริมที่เลือก โดยราคาจะคำนวณ realtime ในหน้า Customize',
    answerEN: 'Price depends on style (Classic/Chibi/Realistic), base type, and accessories. Real-time pricing shown in the Customizer.',
  },
  {
    question: 'รับงาน B2B หรืองาน Event ไหม?',
    questionEN: 'Do you accept B2B or event orders?',
    answer: 'รับครับ! ขั้นต่ำ 10 ชิ้น ราคาพิเศษ มีบริการออกแบบโลโก้บนฐาน และแพ็คเกจสำหรับแจกงาน Event ติดต่อได้ทาง LINE หรืออีเมล',
    answerEN: 'Yes! Minimum 10 pcs with special pricing. Custom logo bases and event packaging available. Contact via LINE or email.',
  },
  {
    question: 'จ่ายเงินยังไงได้บ้าง?',
    questionEN: 'What payment methods do you accept?',
    answer: 'รับ PromptPay QR, บัตรเครดิต/เดบิต (Visa/MC), และโอนเงินผ่านธนาคารพร้อมแนบสลิป',
    answerEN: 'We accept PromptPay QR, Credit/Debit cards (Visa/MC), and bank transfer with slip.',
  },
  {
    question: 'รับงานเร่งด่วนได้ไหม?',
    questionEN: 'Can you do rush orders?',
    answer: 'รับ Rush Order ครับ ระยะเวลา 3–5 วันทำการ มีค่าบริการ +300 บาท ต้องแจ้งล่วงหน้าในช่องหมายเหตุตอนสั่ง',
    answerEN: 'Rush orders available in 3–5 business days for an extra +300 THB. Mention in the order notes.',
  },
  {
    question: 'ห่อของขวัญและส่งตรงให้คนรับได้ไหม?',
    questionEN: 'Can you gift wrap and ship directly to recipient?',
    answer: 'ได้เลยครับ! มีบริการห่อของขวัญสวยงาม พร้อมการ์ดข้อความ (+30 บาท) ใส่ชื่อที่อยู่ผู้รับในระหว่าง Checkout ได้เลย',
    answerEN: 'Yes! Gift wrapping with a message card available (+30 THB). Enter the recipient\'s address at checkout.',
  },
]
